name: Publish Docker image to Docker Hub

on:
    push:
        branches: ['main']

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - name: checkout repository
              uses: actions/checkout@v4

            - name: Log in to the Docker hub
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              id: docker-hub
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}  
                run: |
                  docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build the Docker image
              id: build-docker-image
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hit-counter-image:latest .

            - name: push the Docker image
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hit-counter-image:latest



